FROM mcr.microsoft.com/mmlspark/release

LABEL name="Container image with MML Spark and Jupyter"

WORKDIR /MySpark

COPY requirements.txt .
COPY ./MySpark .

RUN apt-get update && apt-get install -y \
    python3-pip
RUN pip3 install -r requirements.txt

# Add Tini
ENV TINI_VERSION v0.19.0
ADD https://github.com/krallin/tini/releases/download/${TINI_VERSION}/tini /tini
RUN chmod +x /tini
ENTRYPOINT ["/tini", "--"]

EXPOSE 8888
CMD ["jupyter", "notebook", "--port=8888", "--no-browser", "--allow-root", "--ip=0.0.0.0"]
