# set base image
FROM julia:latest

# image description
LABEL name="Container image with Jupyter Notebook and Julia"

# set the working directory in the container
WORKDIR /MyJulia

# copy the local directory containing the dependencies file and the jupyter configuration file
COPY ./MyJulia .

# install dependencies and configure jupyter
RUN apt-get update && apt-get install -y \
    python3-pip
RUN pip3 install -r requirements.txt
RUN julia ConfigureJupyter.jl

# Prepare jupyter notebook
EXPOSE 8888
CMD ["jupyter", "notebook", "--port=8888", "--no-browser", "--allow-root", "--ip=0.0.0.0"]